// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wywygadybzozyakunzng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5d3lnYWR5Ynpvenlha3Vuem5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjI5OTAsImV4cCI6MjA2NTczODk5MH0.9GidCTQUTLByMatBOisbfZPZeTsb7KCgjAozOvdEvMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);